M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu20.04.1} date pet 22 dec 2023 19:52:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-22T19:52:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X114.3Y-50.8
X114.3Y-86.8
T2
X81.765Y-104.14
T0
M30
